sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jyotijaiswal88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jyotijaiswal88/react-test npm test

after success:
  - docker build -t jyotijaiswal88/multi-client ./client
  - docker build -t jyotijaiswal88/multi-nginx ./nginx
  - docker build -t jyotijaiswal88/multi-server ./server
  - docker build -t jyotijaiswal88/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$Docker_ID" --password-stdin
  # take images and push to docker hub push
  - docker push jyotijaiswal88/multi-client
  - docker push jyotijaiswal88/multi-nginx
  - docker push jyotijaiswal88/multi-server
  - docker push jyotijaiswal88/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-app
  env: MultiDockerApp-env
  bucket_name: elasticbeanstalk-us-east-2-861729459927
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    